apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
  type: 
    NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http